version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend/app/src:/app/src
    restart: always
    depends_on:
      - db
  
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/app/src:/app/src
    restart: always
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'